version: '3.7'
services:
  db:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lemp_db
      - MYSQL_USER=lemp
      - MYSQL_PASSWORD=lemp
    command:
      'mysqld --innodb-flush-method=fsync'

  nginx:
    build:
      context: ./nginx/
#    image: nginx:alpine
    container_name: nginx
    networks:
      - nginx_net
    restart: always
    volumes:
      - ./web/:/var/www
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dev/conf:/etc/nginx/conf:ro
      - ./nginx/dev/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/dev/sites-available:/etc/nginx/sites-available:ro
      - ./nginx/dev/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/dev/log:/var/log/nginx
      - ./ssl/dev:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
#
#  pma:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - "8000:80"

#  adminer:
#    image: adminer
#    container_name: adminer
#    restart: always
#    volumes:
#      - ./adminer/adminer.css:/var/www/html/adminer.css
#    ports:
#      - 8080:8080

#  jira:
#    depends_on:
#      - db
#    container_name: jira
#    restart: always
#    image: cptactionhank/atlassian-jira:latest
#    ports:
#      - '8080:8080'
#    volumes:
#      - ./jira/:/var/atlassian/jira  # JIRA_HOME

  mdolnicek.eu:
    build:
      context: ./web/mdolnicek.eu/
      args:
        USER: "${USER}"
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    container_name: mdolnicek.eu
    networks:
      - nginx_net
    volumes:
      - ./web/mdolnicek.eu:/var/www/mdolnicek.eu
    command: tail -F anything

networks:
  nginx_net:
    name: nginx_net